PACKAGE = assignable
CUR_PACK = purse

SOURCE  = \
	HeureException.purse \
	Heure.purse \
	HeureException.purse \
	DateException.purse \
	Date.purse \
	PartnerID.purse \
	SalerID.purse \
	Currencies.purse \
	ExchangeSession.purse \
	ExchangeRecord.purse \
	AccessConditionException.purse \
	AccessCondition.purse \
	AccessControl.purse \
	AccessControlTable.purse \
	AllowedLoyaltyException.purse \
	AllowedLoyalty.purse \
	LoyaltiesTableException.purse \
	LoyaltiesTable.purse \

MAIN       = \
	CheckModClause

include $(CHASE_HOME)/Makefile
