PACKAGE = assignable

SOURCE  = \
        ASTContext.java \
        Assignable.java \
        CheckModClause.java \
        Util.java \

MAIN       = \
	CheckModClause

include $(JAVA_DEV_ROOT)/Makefile
