PACKAGE = assignable
CUR_PACK = pacapinterfaces

SOURCE  = \
	TransactionInterface.pacapinterfaces \
	PurseLoyaltyInterface.pacapinterfaces \
	LoyaltyPurseInterface.pacapinterfaces \
	LoyaltyLoyaltyInterface.pacapinterfaces \

MAIN       = \
        CheckModClause

include $(CHASE_HOME)/Makefile
