PACKAGE = assignable
CUR_PACK = utils

SOURCE = \
	Annee.utils \
	Mois.utils \
	Jour.utils \
	PacapException.utils \
	DecimalException.utils \
	Decimal.utils \

MAIN       = \
        CheckModClause

include $(CHASE_HOME)/Makefile
